image: golang:1.21.3

stages:
  - test
  - build

before_script:
  - cd src/api

lint:
  stage: test
  script:
    - go vet ./... # this is golang slang for recursively find all packages

unit-test:
  stage: test
  script:
    - go test -v ./...

build:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_GITEA_KEY | docker login -u distro --password-stdin git.dbyte.xyz
    - cd src/api
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_SHORT_SHA"
        echo "Running on commit '$CI_COMMIT_SHORT_SHA': tag = $tag"
      fi
    - docker build --pull -t "git.dbyte.xyz/distro/prospector/api${tag}" .
    - docker push "git.dbyte.xyz/distro/prospector/api${tag}"
