image: golang:1.21.3

stages:
  - test
  - build
  - review
  - deploy_canary
  - deploy_prod

before_script:
  - cd src/api

lint:
  stage: test
  script:
    - go vet .

unit-test:
  stage: test
  script:
    - go test -v

# build:
#   stage: build
#   dependencies:
#     - lint
#     - unit-test
#   script:
#     - go build -o prospector .
#     - echo $CI_JOB_ID > build_job_id
#   artifacts:
#     paths:
#       - src/api/prospector
#       - src/api/build_job_id
#     expire_in: 1 week

build:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_GITEA_KEY | docker login -u distro --password-stdin git.dbyte.xyz
    - cd src/api
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_SHORT_SHA"
        echo "Running on commit '$CI_COMMIT_SHORT_SHA': tag = $tag"
      fi
    - docker build --pull -t "git.dbyte.xyz/distro/prospector/api${tag}" .
    - docker push "git.dbyte.xyz/distro/prospector/api${tag}"

deploy_canary:
  image: git.dbyte.xyz/distro/levant
  stage: deploy_canary
  dependencies:
    - build
  script:
    - tools/deploy-canary.sh
  only:
    - master
  environment:
    name: canary
    url: https://canary.prospector.ie

deploy_prod:
  image: multani/nomad
  stage: deploy_prod
  dependencies:
    - build
  script:
    - nomad job promote -address=http://nomad.service.consul:4646 prospector-api
  only:
    - master
  environment:
    name: production
    url: https://prospector.ie

deploy_review:
  image: git.dbyte.xyz/distro/levant
  stage: review
  dependencies:
    - build
  script:
    - tools/deploy-review.sh
  except:
    - master
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.prospector.ie
    on_stop: stop_review

stop_review:
  image: multani/nomad
  stage: review
  before_script:
    - echo "null"
  variables:
    GIT_STRATEGY: none
  script:
    - nomad status -address=http://nomad.service.consul:4646
    - nomad job stop -address=http://nomad.service.consul:4646 -purge prospector-api-${CI_ENVIRONMENT_SLUG}
  except:
    - master
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
