stages:
  - build

before_script:
  - cd src/frontend

build:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_GITEA_KEY | docker login -u distro --password-stdin git.dbyte.xyz
    - cd src/frontend
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_SHORT_SHA"
        echo "Running on commit '$CI_COMMIT_SHORT_SHA': tag = $tag"
      fi
    - docker pull git.dbyte.xyz/distro/prospector/frontend:latest || true
    - docker build --cache-from git.dbyte.xyz/distro/prospector/frontend:latest --pull --tag "git.dbyte.xyz/distro/prospector/frontend${tag}" .
    - docker push "git.dbyte.xyz/distro/prospector/frontend${tag}"
