basePath: /api
definitions:
  controllers.Message:
    properties:
      message:
        type: string
    type: object
host: prospector.ie
info:
  contact: {}
  description: API backend for Prospector
  title: Prospector API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check if the API is up and running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Message'
      summary: Health check
      tags:
      - health
schemes:
- https
swagger: "2.0"
