basePath: /api
host: prospector.ie
info:
  contact: {}
  description: API for Prospector, a tool for deploying and managing Nomad jobs
  title: Prospector API
  version: "0"
paths:
  /health:
    get:
      description: Healthcheck endpoint for the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Healthcheck
schemes:
- https
swagger: "2.0"
